modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="chunchunmaru"
version="1.1.2"
displayName="chunchunmaru"
credits="Chunchunmaru"
displayURL="https://github.com/TheNwkos/chunchunmaru"
authors="Note, Razomi"
description='''
Chunchunmaru that's it :)
'''

[[dependencies.chunchunmaru]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




